In [1]:
import numpy as np
import pandas as pd
import time # For setting up time delays between queries
from nba_api.stats.static import teams # For team list; "pip install nba_api"
from nba_api.stats.endpoints import teamplayerdashboard

In [45]:
# Query nba.live.endpoints.scoreboard and  list games in localTimeZone
from datetime import datetime, timezone
from dateutil import parser
from nba_api.live.nba.endpoints import scoreboard

f = "{gameId}: {awayTeam} vs. {homeTeam}" 

board = scoreboard.ScoreBoard()
print("ScoreBoardDate: " + board.score_board_date)
games = board.games.get_dict()
for game in games:
    print(f.format(gameId=game['gameId'], awayTeam=game['awayTeam']['teamTricode'], homeTeam=game['homeTeam']['teamTricode']))

ScoreBoardDate: 2023-02-07
0022200821: OKC vs. LAL
0022200816: NYK vs. ORL
0022200817: PHX vs. BKN
0022200818: ATL vs. NOP
0022200819: CHI vs. MEM
0022200820: MIN vs. DEN

In [41]:
#function to get the team_id in order for us to retrieve the team stats
def get_team_id(team_name_abbrev):
    nba_teams=teams.get_teams()
    return [team for team in nba_teams
         if team['abbreviation'] == team_name_abbrev][0]['id']

1610612747

In [46]:
# Below returns a list of dictionaries, 1 for each NBA tram
nba_teams=teams.get_teams()

# Let's create a Pandas DataFrame using extracted list of dictionaries
df_nba_teams=pd.DataFrame(nba_teams)

# Print DataFrame
df_nba_teams.head()

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Atlanta,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966

In [47]:
LAL_stats=teamplayerdashboard.TeamPlayerDashboard(team_id=get_team_id('LAL'), 
                                         season='2022-23', 
                                         season_type_all_star='Regular Season'
                                         )
df_LAL_stats=LAL_passes.get_data_frames()[1]

In [48]:
columns_needed = ['GROUP_SET', 'PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'GP', 'W', 'L',
       'W_PCT', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT',
       'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL',
       'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS', 'NBA_FANTASY_PTS']

In [49]:
df_LAL_stats[columns_needed]

,GROUP_SET,PLAYER_ID,PLAYER_NAME,NICKNAME,GP,W,L,W_PCT,MIN,FGM,...,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS
0,Players,203076,Anthony Davis,Anthony,30,14,16,0.467,1005.651667,303,...,77,61,38,61,28,80,174,814,50,1598.7
1,Players,1630559,Austin Reaves,Austin,36,17,19,0.472,1038.800000,124,...,80,49,20,14,9,60,112,388,71,694.2
2,Players,1631306,Cole Swider,Cole,5,1,4,0.200,37.060000,3,...,4,0,0,0,0,3,1,9,-1,23.4
3,Players,1627745,Damian Jones,Damian,22,6,16,0.273,176.335000,20,...,4,9,3,12,6,17,19,55,-34,163.0
4,Players,203471,Dennis Schroder,Dennis,40,21,19,0.525,1233.430000,156,...,163,65,31,5,29,91,105,484,9,901.1
5,Players,1629308,Juan Toscano-Anderson,Juan,30,12,18,0.400,364.871667,33,...,25,17,10,7,6,46,21,81,-85,225.7
6,Players,1629134,Kendrick Nunn,Kendrick,39,18,21,0.462,527.845000,102,...,34,31,11,3,13,35,18,262,-21,390.0
7,Players,2544,LeBron James,LeBron,43,21,22,0.488,1568.860000,497,...,306,134,40,24,39,69,225,1290,103,2246.2
8,Players,1629022,Lonnie Walker IV,Lonnie,37,15,22,0.405,1040.570000,186,...,48,34,26,12,14,60,53,514,-155,764.4
9,Players,1630346,Matt Ryan,Matt,12,5,7,0.417,129.168333,15,...,4,3,2,0,0,14,5,47,0,72.8
10,Players,1631108,Max Christie,Max,33,14,19,0.424,479.263333,43,...,17,11,7,6,5,31,9,124,-69,263.9
11,Players,201976,Patrick Beverley,Patrick,44,21,23,0.477,1187.460000,95,...,113,39,40,25,9,121,63,281,-91,773.3
12,Players,1629060,Rui Hachimura,Rui,6,3,3,0.500,160.631667,26,...,3,1,3,1,7,6,11,68,14,127.9
13,Players,201566,Russell Westbrook,Russell,51,25,26,0.490,1463.310000,294,...,383,178,51,22,65,120,150,800,-48,1795.9
14,Players,1630590,Scotty Pippen Jr.,Scotty,6,1,5,0.167,31.516667,4,...,2,2,2,1,2,3,6,14,-1,28.8
15,Players,1628425,Sterling Brown,Sterling,4,2,2,0.500,24.363333,0,...,2,0,3,0,1,4,0,0,-4,21.6
16,Players,1628418,Thomas Bryant,Thomas,40,21,19,0.525,858.983333,195,...,28,28,14,22,28,77,81,492,-37,942.8
17,Players,1628972,Troy Brown Jr.,Troy,48,22,26,0.458,1158.405000,124,...,48,33,36,8,16,71,30,331,-25,743.2
18,Players,1629117,Wenyen Gabriel,Wenyen,42,20,22,0.476,648.475000,113,...,19,30,15,25,11,92,67,270,-16,586.5